[package]
name = "paraeq-dsp"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
realfft = { workspace = true }
rustfft = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
approx = { workspace = true }
biquad = "0.6"
proptest = { workspace = true }
serde_json = { workspace = true }
