[package]
name = "paraeq-desktop"
edition.workspace = true
license.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
log = { workspace = true }
paraeq-coreaudio = { path = "../../crates/paraeq-coreaudio" }
paraeq-dsp = { path = "../../crates/paraeq-dsp" }
paraeq-engine = { path = "../../crates/paraeq-engine" }
serde = { workspace = true }
serde_json = { workspace = true }
tauri = { version = "2", features = ["tray-icon"] }

[dev-dependencies]
tempfile = "3"
